#!/bin/bash
# Generates cloud init files from properties
# @author Daniel Bernstein
USAGE="Usage: propertyFile outputFilePrefix"

if [  ! -n "$1" ]
then
  echo $USAGE
  exit 1
fi

if [  ! -n "$2" ]
then
  echo $USAGE
  exit 1
fi

if [  ! -f $inputFile ] 
then
  echo $inputFile does not exist
  echo $USAGE
  exit 1
fi

inputFile=$1
outputFilePrefix=$2
producerCloudInit=userdata-cloud-init-multimime-producer
workerCloudInit=userdata-cloud-init-multimime-worker



for j in $producerCloudInit $workerCloudInit; do 
  file=$j.txt.template
  echo Processing $j


  fileAsString="$(<$file)"
  
  for i in `cat $inputFile`; do
  echo filtering $i;
  name='${'$(echo $i| cut -d'=' -f1)'}'
  value=$(echo $i| cut -d'=' -f2) 
  echo replacing $name  with $value
  
  fileAsString=`echo "$fileAsString" | sed "s/$name/$value/g"`
  done;
  echo "$fileAsString" > $outputFilePrefix-$j.txt;
done;
